[dependencies]
"php/php" = "=8.3.4-rc.2"

[fs]
"/app" = "app"
"/vendor" = "vendor"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["/app/index.php"]
